#ifndef UI_H
#define UI_H

#define UI_PADDING_ALL 8

/* Media */
#define UI_MEDIA_TILEVIEW_HIGHT LCD_V_RES - UI_MEDIA_FOOTER_HIGHT - 3 * UI_PADDING_ALL
#define UI_MEDIA_FOOTER_HIGHT 120
#define UI_MEDIA_ALBUM_ART_WIDTH 480
#define UI_MEDIA_ALBUM_ART_HIGHT 240

#endif